---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/questions":
    get:
      summary: Retrieves all questions
      tags:
      - Questions
      responses:
        '200':
          description: questions found
          content:
            application/json:
              schema:
                type: array
                items:
                  text:
                    type: string
                  options:
                    type: array
                    items:
                      type: string
                  answer:
                    type: string
                  score:
                    type: integer
                required:
                - text
                - options
                - answer
                - score
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
